-- local EventFrame = CreateFrame("Frame")
-- EventFrame:RegisterEvent("PLAYER_LOGIN")
-- EventFrame:SetScript("OnEvent", function(self,event,...) 
-- 	if type(ArchCharDB) ~= "number" then
-- 		ArchCharDB = 1;
-- 		ChatFrame1:AddMessage('Welcome '.. UnitName("Player") .. ' this is your first login with Archrist addon please use /arch to configure');
-- 	else
-- 		if ArchCharDB then
-- 			ChatFrame1:AddMessage('Welcome '.. UnitName("Player") .. " you have entered world " ..  ArchCharDB .. " times before.");
-- 		end
-- 		ArchCharDB = ArchCharDB + 1;
-- 	end
-- end)

-- --[[
--     CreateFrame Arguments:
--         1- The type of frame - 'frame'
--         2- The global frame name 
--         3- The parent frame (not a string)
--         4- A comma separated list (string list) of xml templates to inherit from
-- ]]

-- UIConfig.SetSize(300, 360);
-- UIConfig.SetPoint("CENTER", UIParent, "CENTER"); -- point, relativeFrame, relativePoint, xOffset, yOffset

-- --[[
--     "TOPLEFT"
--     "TOP"
--     "TOPRIGHT"
--     "LEFT"
--     "CENTER"
--     "RIGHT"
--     "BOTTOMLEFT"
--     "BOTTOM"
--     "BOTTOMRIGHT"
-- ]]
